### ISSUE TITLE
Create new issue templates

### ISSUE THREAD

**Issue by MegTheDev** [lansingcodes/organizer-resources#10]
Create new issue templates for Bug Reports and Feature Requests that match the templates in the www project.

Acceptance Criteria
- [x]  .github/ISSUE_TEMPLATE/bug_report.md matches the file of the same name in www
- [x]  .github/ISSUE_TEMPLATE/feature_request.md matches the file of the same name in www
- [x]  The New Issue page shows two issue types: Bug report and Feature request
- [x]  Clicking Get Started next to Bug report fills the issue description with the content of the bug_report.md file
- [x]  Clicking Get Started next to Feature request fills the issue description with the content of the feature_request.md file

**Comment by egillespie** [comment]
I merged the changes and verified that the New Issue workflow includes the two issue types and templates. All done here! 🥳
